name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - wbfy
      - renovate/**
jobs:
  test:
    uses: WillBooster/reusable-workflows/.github/workflows/test.yml@main
    with:
      dot_env_path: .env
    secrets:
      DOT_ENV: FIREBASE_PROJECT_ID=test
      GH_TOKEN: ${{ secrets.PUBLIC_GH_BOT_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
